### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by dohomi** [contentful-labs/contentful-aws-lambda-static#1]
Hello,
I'd like to know if there is any more effort planned in a showcase of lambda / serverless static file packaging with contentful?
Cheers

**Comment by mariobodemann** [comment]
Hey,

right now we do not have anything planned with this repository. If you want to see some more static side generators: take a look at our [documentation about static site generators](https://www.contentful.com/developers/docs/tools/staticsitegenerators/)

If you have any specific ideas, you would like us to write about, please feel free to report back here ... :)

Mario
